In [1]:
from datascience import *
import numpy as np

## Review of Tables ##

In [2]:
skyscrapers = Table.read_table('skyscrapers.csv')
skyscrapers

name                              | material  | city          | height | completed
One World Trade Center            | composite | New York City | 541.3  | 2014
Willis Tower                      | steel     | Chicago       | 442.14 | 1974
432 Park Avenue                   | concrete  | New York City | 425.5  | 2015
Trump International Hotel & Tower | concrete  | Chicago       | 423.22 | 2009
Empire State Building             | steel     | New York City | 381    | 1931
Bank of America Tower             | composite | New York City | 365.8  | 2009
Stratosphere Tower                | concrete  | Las Vegas     | 350.22 | 1996
Aon Center                        | steel     | Chicago       | 346.26 | 1973
John Hancock Center               | steel     | Chicago       | 343.69 | 1969
WITI TV Tower                     | steel     | Shorewood     | 329    | 1962
... (190 rows omitted)

In [3]:
skyscrapers.select('name', 'height')

name                              | height
One World Trade Center            | 541.3
Willis Tower                      | 442.14
432 Park Avenue                   | 425.5
Trump International Hotel & Tower | 423.22
Empire State Building             | 381
Bank of America Tower             | 365.8
Stratosphere Tower                | 350.22
Aon Center                        | 346.26
John Hancock Center               | 343.69
WITI TV Tower                     | 329
... (190 rows omitted)

In [4]:
skyscrapers.drop('completed', 'height', 'material')

name                              | city
One World Trade Center            | New York City
Willis Tower                      | Chicago
432 Park Avenue                   | New York City
Trump International Hotel & Tower | Chicago
Empire State Building             | New York City
Bank of America Tower             | New York City
Stratosphere Tower                | Las Vegas
Aon Center                        | Chicago
John Hancock Center               | Chicago
WITI TV Tower                     | Shorewood
... (190 rows omitted)

In [9]:
skyscrapers.show(5)

In [6]:
skyscrapers.where('city', 'Los Angeles')

name                  | material | city        | height | completed
U.S. Bank Tower       | steel    | Los Angeles | 310.29 | 1990
Aon Center            | steel    | Los Angeles | 261.52 | 1974
Two California Plaza  | steel    | Los Angeles | 228.6  | 1992
Gas Company Tower     | steel    | Los Angeles | 228.3  | 1991
Bank of America Plaza | steel    | Los Angeles | 224.03 | 1975
777 Tower             | steel    | Los Angeles | 221    | 1991
Wells Fargo Tower     | steel    | Los Angeles | 220.37 | 1983
Figueroa at Wilshire  | steel    | Los Angeles | 218.54 | 1989
City National Tower   | steel    | Los Angeles | 213.06 | 1971
Paul Hastings Tower   | steel    | Los Angeles | 213.06 | 1971
... (1 rows omitted)

In [7]:
skyscrapers.where('name', 'Empire State Building')

name                  | material | city          | height | completed
Empire State Building | steel    | New York City | 381    | 1931

In [8]:
skyscrapers.where('city', 'New York City').sort('completed')

name                    | material | city          | height | completed
Metropolitan Life Tower | steel    | New York City | 213.36 | 1909
Woolworth Building      | steel    | New York City | 241.4  | 1913
Chanin Building         | steel    | New York City | 197.8  | 1929
Mercantile Building     | steel    | New York City | 192.6  | 1929
Chrysler Building       | steel    | New York City | 318.9  | 1930
The Trump Building      | steel    | New York City | 282.55 | 1930
One Grand Central Place | steel    | New York City | 205.13 | 1930
Empire State Building   | steel    | New York City | 381    | 1931
Twenty Exchange         | steel    | New York City | 225.86 | 1931
500 Fifth Avenue        | steel    | New York City | 212.45 | 1931
... (63 rows omitted)

In [9]:
skyscrapers.where('city', 'New York City').sort('completed', descending=True)

name                                             | material       | city          | height | completed
432 Park Avenue                                  | concrete       | New York City | 425.5  | 2015
Sky                                              | concrete       | New York City | 206    | 2015
One World Trade Center                           | composite      | New York City | 541.3  | 2014
One57                                            | steel/concrete | New York City | 306.07 | 2014
4 World Trade Center                             | composite      | New York City | 297.73 | 2014
Courtyard & Residence Inn Manhattan/Central Park | concrete       | New York City | 229.62 | 2013
Eight Spruce Street                              | concrete       | New York City | 265.18 | 2011
1 MiMA Tower                                     | concrete       | New York City | 194.55 | 2011
Goldman Sachs Headquarters                       | steel          | New York City | 228.3  | 2010
Langham Place                                    | concrete       | New York City | 192.58 | 2010
... (63 rows omitted)

In [10]:
chicago = skyscrapers.where('city', 'Chicago').drop('city')
chicago

name                              | material       | height | completed
Willis Tower                      | steel          | 442.14 | 1974
Trump International Hotel & Tower | concrete       | 423.22 | 2009
Aon Center                        | steel          | 346.26 | 1973
John Hancock Center               | steel          | 343.69 | 1969
The Franklin - North Tower        | composite      | 306.94 | 1989
Two Prudential Plaza              | concrete       | 303.28 | 1990
311 South Wacker Drive            | concrete       | 292.92 | 1990
900 North Michigan Avenue         | concrete/steel | 265    | 1989
Water Tower Place                 | concrete       | 261.88 | 1976
Aqua                              | concrete       | 261.75 | 2009
... (26 rows omitted)

In [12]:
chicago.where('material', 'steel').sort('completed', descending=True)

name                    | material | height | completed
Willis Tower            | steel    | 442.14 | 1974
Aon Center              | steel    | 346.26 | 1973
John Hancock Center     | steel    | 343.69 | 1969
Chase Tower             | steel    | 259.08 | 1969
Richard J. Daley Center | steel    | 197.51 | 1965

## Numbers ##

In [10]:
4 * 5 

20

In [11]:
20  # int

20

In [12]:
20 / 3  # float

6.666666666666667

In [13]:
20 / 2  # also a float

10.0

In [14]:
1234 ** 5

2861381721051424

In [28]:
123456789 ** 1234

ValueError: Exceeds the limit (4300 digits) for integer string conversion; use sys.set_int_max_str_digits() to increase the limit

In [20]:
4 / 700

0.005714285714285714

In [29]:
4 / 700000000000000000

5.714285714285714e-18

In [30]:
0.12345678901234567890123456789

0.12345678901234568

In [31]:
0.12345678901234567890123456789 - 0.1234567890123456789

0.0

In [32]:
10 ** 0.5

3.1622776601683795

In [33]:
16 ** 0.5

4.0

In [34]:
(10 ** 0.5) ** 2

10.000000000000002

In [35]:
20 / 10

2.0

In [36]:
int(20 / 10)

2

In [37]:
int(20 / 9)

2

In [38]:
float(3)

3.0

In [39]:
6 / 4

1.5

In [40]:
6 / 4000

0.0015

In [41]:
6 / 400000000000000000000000000000000000000000000000000000000

1.5e-56

In [42]:
400000000000000000000000000000000000000000000000000000000 * 1.5e-56 

6.0

In [43]:
1.5e-56 

1.5e-56

In [48]:
x = 5

In [49]:
2x

SyntaxError: invalid decimal literal (207285602.py, line 1)

In [50]:
2 * x

10

In [51]:
round(3.7)

4

In [52]:
round(2.00000052345324, 2)

2.0

In [53]:
10 * 3.0

30.0

## Strings ##

In [54]:
'baby yoda'

'baby yoda'

In [55]:
"baby yoda isn't yoda"

"baby yoda isn't yoda"

In [56]:
'baby yoda isn't yoda'

SyntaxError: unterminated string literal (detected at line 1) (2037818190.py, line 1)

In [57]:
'straw' + 'berry' # concatenation

'strawberry'

In [58]:
'straw' + ' ' + 'berry'

'straw berry'

In [59]:
'ha' * 10

'hahahahahahahahahaha'

In [60]:
'lo' * 5.5

TypeError: can't multiply sequence by non-int of type 'float'

In [61]:
int('3')

3

In [62]:
int('3.0')

ValueError: invalid literal for int() with base 10: '3.0'

In [63]:
float('3.0')

3.0

In [64]:
str(3)

'3'

In [65]:
str(4.5)

'4.5'

In [66]:
x = 3
y = '4'
z = '5.6'

In [67]:
x + y

TypeError: unsupported operand type(s) for +: 'int' and 'str'

In [68]:
x + int(y + z)

ValueError: invalid literal for int() with base 10: '45.6'

In [69]:
str(x) + int(y)

TypeError: can only concatenate str (not "int") to str

In [70]:
y + float(z)

TypeError: can only concatenate str (not "float") to str

## Types ##

In [71]:
type(10)

int

In [72]:
a = 10
type(a)

int

In [73]:
type(4.5)

float

In [74]:
type('abc')

str

In [75]:
type(skyscrapers)

datascience.tables.Table

In [76]:
type(True)

bool

In [77]:
type(abs)

builtin_function_or_method

## Arrays ##

In [78]:
my_array = make_array(1, 2, 3, 4)

In [86]:
my_array?

Type:        ndarray
String form: [1 2 3 4]
Length:      4
File:        d:\software\anaconda3\lib\site-packages\numpy\__init__.py
Docstring:  
ndarray(shape, dtype=float, buffer=None, offset=0,
        strides=None, order=None)

An array object represents a multidimensional, homogeneous array
of fixed-size items.  An associated data-type object describes the
format of each element in the array (its byte-order, how many bytes it
occupies in memory, whether it is an integer, a floating point number,
or something else, etc.)

Arrays should be constructed using `array`, `zeros` or `empty` (refer
to the See Also section below).  The parameters given here refer to
a low-level method (`ndarray(...)`) for instantiating an array.

For more information, refer to the `numpy` module and examine the
methods and attributes of an array.

Parameters
----------
(for the __new__ method; see Notes below)

shape : tuple of ints
    Shape of created array.
dtype : data-type, optional
    Any object that ca

In [87]:
type(my_array)

numpy.ndarray

In [88]:
my_array * 2

array([2, 4, 6, 8], dtype=int64)

In [89]:
my_array ** 2

array([ 1,  4,  9, 16], dtype=int64)

In [90]:
my_array + 1

array([2, 3, 4, 5], dtype=int64)

In [91]:
my_array # array is unchanged

array([1, 2, 3, 4], dtype=int64)

In [92]:
len(my_array)

4

In [93]:
sum(my_array)

10

In [94]:
len(my_array) / sum(my_array)

0.40000000000000002

In [95]:
another = make_array(60, 70, 80, 90)

In [96]:
my_array + another

array([61, 72, 83, 94], dtype=int64)

In [97]:
yet_another = make_array(5, 6, 7)

In [98]:
my_array + yet_another

ValueError: operands could not be broadcast together with shapes (4,) (3,) 

In [99]:
tunas = make_array('bluefin', 'albacore', 'jim')
tunas

array(['bluefin', 'albacore', 'jim'],
      dtype='<U8')

In [100]:
sum(my_array)

10

In [101]:
np.average(my_array)

2.5

In [102]:
len(my_array)

4

## Columns of Tables are Arrays ##

In [104]:
sf = skyscrapers.where('city', 'San Francisco')
sf

name                  | material  | city          | height | completed
Transamerica Pyramid  | composite | San Francisco | 260    | 1972
555 California Street | steel     | San Francisco | 237.44 | 1969
345 California Center | steel     | San Francisco | 211.84 | 1986
Millennium Tower      | concrete  | San Francisco | 196.6  | 2009

In [105]:
sf.select('height')

height
260
237.44
211.84
196.6

In [106]:
sf.column('height')

array([ 260.        ,  237.44000244,  211.83999634,  196.6000061 ])

In [108]:
np.average(sf.column('height'))

226.470001220705

In [109]:
la = skyscrapers.where('city', 'Los Angeles')

In [110]:
np.average(la.column('height')) - np.average(sf.column('height'))

4.6254522150195498